packages: []
catalogs:
  build:
    '@nuxt/devtools': ^3.0.0-beta.2
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.2.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.4
    '@unocss/nuxt': ^66.5.4
    '@vite-pwa/nuxt': ^1.0.7
    '@vueuse/nuxt': ^14.0.0
    nuxt: ^4.2.0
    unocss: ^66.5.4
    unplugin: ^2.3.10
    vite: ^7.1.12
  dev:
    '@antfu/eslint-config': ^6.1.0
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.2
  frontend:
    '@vueuse/core': ^14.0.0
    pinia: ^3.0.3
    vue: ^3.5.22
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/twemoji': ^1.2.4
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
